<a href="https://colab.research.google.com/github/Gudimetla-Sri-Lakshmi-Satya-Navya/FML-lab/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
X, y = load_digits(return_X_y=True)

In [3]:
X.shape, y.shape

((1797, 64), (1797,))

In [4]:
X[0], y[0]

(array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]),
 0)

In [5]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

(array([ 0.,  0.,  0.,  9., 15.,  2.,  0.,  0.,  0.,  0.,  5., 16., 11.,
         1.,  0.,  0.,  0.,  0., 13., 15.,  1.,  0.,  0.,  0.,  0.,  2.,
        16., 11.,  0.,  0.,  0.,  0.,  0.,  2., 16., 11.,  4.,  4.,  0.,
         0.,  0.,  2., 15., 16., 16., 14., 10.,  1.,  0.,  0.,  9., 16.,
         7.,  3., 15.,  6.,  0.,  0.,  0.,  7., 15., 16., 16.,  6.]),
 5.375,
 6.3356629487370935)

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [ ]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

In [12]:
model = LogisticRegression(C=0.05, multi_class='ovr',random_state=0)
model.fit(X_train, y_train)

LogisticRegression(C=0.05, multi_class='ovr', random_state=0)

In [13]:
X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

In [14]:
model.score(X_train, y_train)

0.9707724425887265

In [15]:
model.score(X_test, y_test)

0.8888888888888888

In [16]:
confusion_matrix(y_test, y_pred)

array([[27,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 34,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  3, 30,  0,  0,  0,  0,  0,  3,  0],
       [ 0,  0,  0, 25,  0,  0,  0,  0,  3,  1],
       [ 0,  6,  0,  0, 16,  0,  2,  2,  3,  1],
       [ 0,  1,  0,  0,  0, 37,  0,  0,  1,  1],
       [ 0,  1,  0,  0,  0,  0, 42,  0,  1,  0],
       [ 0,  1,  0,  0,  0,  0,  0, 35,  3,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0, 38,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  5, 36]])

In [18]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        27
           1       0.72      0.97      0.83        35
           2       1.00      0.83      0.91        36
           3       1.00      0.86      0.93        29
           4       1.00      0.53      0.70        30
           5       1.00      0.93      0.96        40
           6       0.95      0.95      0.95        44
           7       0.95      0.90      0.92        39
           8       0.66      0.97      0.78        39
           9       0.92      0.88      0.90        41

    accuracy                           0.89       360
   macro avg       0.92      0.88      0.89       360
weighted avg       0.92      0.89      0.89       360

