<a href="https://colab.research.google.com/github/Gudimetla-Sri-Lakshmi-Satya-Navya/FML-lab/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array ([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0]=5
print(a)
b=np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


In [ ]:
import numpy as np
a=np.zeros((2,2))
b=np.ones((2,2))
c=np.full((2,2),7)
d=np.eye(2)
e=np.random.random((2,2))
print(a)
print(b)
print(c)
print(d)
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.96071864 0.37804214]
 [0.03592779 0.74818878]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)
print(a[0,1])
b[0,0]=77
print(b)

[[2 3]
 [6 7]]
2
[[77  3]
 [ 6  7]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
row_r1 = a[0, :] 
print(row_r1, row_r1.shape)
row_r2 = a[1:2, :] 
print(row_r2, row_r2.shape)
row_r3 = a[[1], :]
print(row_r3, row_r3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([0, 2, 0, 1])
print(b)
print(a[:, b])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]
[[ 1  3  1  2]
 [ 4  6  4  5]
 [ 7  9  7  8]
 [10 12 10 11]]


In [ ]:
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
bool_idx = (a > 2)
print(bool_idx)
x = np.array([1, 2])  
y = np.array([1.0, 2.0])  
z = np.array([1, 2])
print(x.dtype, y.dtype, z.dtype)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
int64 float64 int64


In [ ]:
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(np.sqrt(x))
print(x + y)
print(np.add(x, y))
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x.dot(y))
print(np.dot(x,y))
print(x @ y)
print(np.sum(x))
print(np.sum(x, axis=0))  
print(np.sum(x, axis=1))  

[[19 22]
 [53 62]]
[[19 22]
 [53 62]]
[[19 22]
 [53 62]]
12
[6 6]
[3 9]
